#!/bin/bash
echo -e "\n\t1) Mostrar pelis en el formato indicado"
sed -e 's/<p id=.director.>/Idirector: /Ig' -e 's/<p id=.genres.>/Igeneros: /Ig' -e 's/<. id="writers">/Iguionistas: /Ig' -e 's/<.2>/Titulo: /Ig' -e 's/<p id="rating">/Valoracion: /Ig' -e 's/<p id=.length.>/Iduracion: /Ig' -e 's/m<\/p>/ minutos/Ig' -e 's/<\/p>//Ig' -e 's/<p>/Sinopsis: /Ig' -e 's/<p>/Sinopsis: /Ig' -e '/<\/article>/Id' -e '/<hr>/Id' -e 's/<article>/\t==================================/Ig' -e 's/(20/\n\tAño: 20/Ig' -e 's/)<\/h2>/ /Ig' -e '/<\/body>/Id' -e '/<\/html>/Id' -e '/<!DOCTYPE html>/Id' -e '/html/Id' -e '/<head>/Id' -e '/<title>Films<\/title>/Id' -e '/<\/head>/Id' -e '/<body>/Id' -e '/<h1>Films<\/h1>/Id' -e 's/[|]/, /Ig' -e 's/ratings/valoraciones/Ig' films.html
echo -e "\n\t2) Mostrar el título, el año y la valoración de las películas de los años 2000 (2000-2009)\n"
sed -e 's/<p id=.director.>/Idirector: /Ig' -e 's/<p id=.genres.>/Igeneros: /Ig' -e 's/<. id="writers">/Iguionistas: /Ig' -e 's/<.2>/Titulo: /Ig' -e 's/<p id="rating">/Valoracion: /Ig' -e 's/<p id=.length.>/Iduracion: /Ig' -e 's/m<\/p>/ minutos/Ig' -e 's/<\/p>//Ig' -e 's/<p>/Sinopsis: /Ig' -e 's/<p>/Sinopsis: /Ig' -e '/<\/article>/Id' -e '/<hr>/Id' -e 's/<article>/\t==================================/Ig' -e 's/(20/\n\tAño: 20/Ig' -e 's/)<\/h2>/ /Ig' -e '/<\/body>/Id' -e '/<\/html>/Id' -e '/<!DOCTYPE html>/Id' -e '/html/Id' -e '/<head>/Id' -e '/<title>Films<\/title>/Id' -e '/<\/head>/Id' -e '/<body>/Id' -e '/<h1>Films<\/h1>/Id' -e 's/[|]/, /Ig' -e 's/ratings/valoraciones/Ig' films.html | grep -B 1 -A 1 '200[0-9]'
echo -e "\n\n\t3)  Mostrar las pel ́ıculas formatadas como en 1) pero cambiando el formato del n ́umero de valoracionesde 658000 a 658k\n"
sed -e 's/<p id=.director.>/Idirector: /Ig' -e 's/<p id=.genres.>/Igeneros: /Ig' -e 's/<. id="writers">/Iguionistas: /Ig' -e 's/<.2>/Titulo: /Ig' -e 's/<p id="rating">/Valoracion: /Ig' -e 's/<p id=.length.>/Iduracion: /Ig' -e 's/m<\/p>/ minutos/Ig' -e 's/<\/p>//Ig' -e 's/<p>/Sinopsis: /Ig' -e 's/<p>/Sinopsis: /Ig' -e '/<\/article>/Id' -e '/<hr>/Id' -e 's/<article>/\t==================================/Ig' -e 's/(20/\n\tAño: 20/Ig' -e 's/)<\/h2>/ /Ig' -e '/<\/body>/Id' -e '/<\/html>/Id' -e '/<!DOCTYPE html>/Id' -e '/html/Id' -e '/<head>/Id' -e '/<title>Films<\/title>/Id' -e '/<\/head>/Id' -e '/<body>/Id' -e '/<h1>Films<\/h1>/Id' -e 's/[|]/, /Ig' -e 's/ratings/valoraciones/Ig' -e 's/\([[:digit:]]\{3\}\)\([[:digit:]]\{3\}\)/\1\k/Ig' films.html
echo -e "\n\n\t4) Añadir un punto al final de las líneas que no lo tengan.\n"
sed -e 's/<p id=.director.>/Idirector: /Ig' -e 's/<p id=.genres.>/Igeneros: /Ig' -e 's/<. id="writers">/Iguionistas: /Ig' -e 's/<.2>/Titulo: /Ig' -e 's/<p id="rating">/Valoracion: /Ig' -e 's/<p id=.length.>/Iduracion: /Ig' -e 's/m<\/p>/ minutos/Ig' -e 's/<\/p>//Ig' -e 's/<p>/Sinopsis: /Ig' -e 's/<p>/Sinopsis: /Ig' -e '/<\/article>/Id' -e '/<hr>/Id' -e 's/<article>/\t==================================/Ig' -e 's/(20/\n\tAño: 20/Ig' -e 's/)<\/h2>/ /Ig' -e '/<\/body>/Id' -e '/<\/html>/Id' -e '/<!DOCTYPE html>/Id' -e '/html/Id' -e '/<head>/Id' -e '/<title>Films<\/title>/Id' -e '/<\/head>/Id' -e '/<body>/Id' -e '/<h1>Films<\/h1>/Id' -e 's/[|]/, /Ig' -e 's/ratings/valoraciones/Ig' -e 's/$/\./Ig' films.html
echo -e "\n\n\t5) Mostrar una versión resumida en la que la sinopsis se limita a 300 caracteres\n"
sed -e 's/<p id=.director.>/Idirector: /Ig' -e 's/<p id=.genres.>/Igeneros: /Ig' -e 's/<. id="writers">/Iguionistas: /Ig' -e 's/<.2>/Titulo: /Ig' -e 's/<p id="rating">/Valoracion: /Ig' -e 's/<p id=.length.>/Iduracion: /Ig' -e 's/m<\/p>/ minutos/Ig' -e 's/<\/p>//Ig' -e 's/<p>/Sinopsis: /Ig' -e 's/<p>/Sinopsis: /Ig' -e '/<\/article>/Id' -e '/<hr>/Id' -e 's/<article>/\t==================================/Ig' -e 's/(20/\n\tAño: 20/Ig' -e 's/)<\/h2>/ /Ig' -e '/<\/body>/Id' -e '/<\/html>/Id' -e '/<!DOCTYPE html>/Id' -e '/html/Id' -e '/<head>/Id' -e '/<title>Films<\/title>/Id' -e '/<\/head>/Id' -e '/<body>/Id' -e '/<h1>Films<\/h1>/Id' -e 's/[|]/, /Ig' -e 's/ratings/valoraciones/Ig' films.html | sed -e 's/^\(.\{318\}\).*$/\1.../'